# This is a config for E2B sandbox template.
# You can use template ID (o3h6l7sqvr8zczxtlwqw) or template name (vibe-prateek) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-prateek") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-prateek") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-prateek')

team_id = "975b3c24-c899-4ef9-990a-8069efb61d2f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-prateek"
template_id = "o3h6l7sqvr8zczxtlwqw"
